// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg3JItEme9iaYbNAedQ961ex0A2PtPIgQ',
    appId: '1:1066072433630:web:43b7213e791d694185b34f',
    messagingSenderId: '1066072433630',
    projectId: 'portfolio-d2ea6',
    authDomain: 'portfolio-d2ea6.firebaseapp.com',
    databaseURL: 'https://portfolio-d2ea6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portfolio-d2ea6.firebasestorage.app',
    measurementId: 'G-Y6WVW75GNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk4ssWnrMG_bigW9FiXeN3--gFWcm8Z3U',
    appId: '1:1066072433630:android:3713c9c265e151b885b34f',
    messagingSenderId: '1066072433630',
    projectId: 'portfolio-d2ea6',
    databaseURL: 'https://portfolio-d2ea6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portfolio-d2ea6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzXlv9xpa_Ws6EjV9pZEAYXb8o8N0zJTo',
    appId: '1:1066072433630:ios:b141ab8be1c0378e85b34f',
    messagingSenderId: '1066072433630',
    projectId: 'portfolio-d2ea6',
    databaseURL: 'https://portfolio-d2ea6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portfolio-d2ea6.firebasestorage.app',
    iosBundleId: 'com.example.flutterDevPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzXlv9xpa_Ws6EjV9pZEAYXb8o8N0zJTo',
    appId: '1:1066072433630:ios:b141ab8be1c0378e85b34f',
    messagingSenderId: '1066072433630',
    projectId: 'portfolio-d2ea6',
    databaseURL: 'https://portfolio-d2ea6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portfolio-d2ea6.firebasestorage.app',
    iosBundleId: 'com.example.flutterDevPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg3JItEme9iaYbNAedQ961ex0A2PtPIgQ',
    appId: '1:1066072433630:web:a765d0a7e83e312885b34f',
    messagingSenderId: '1066072433630',
    projectId: 'portfolio-d2ea6',
    authDomain: 'portfolio-d2ea6.firebaseapp.com',
    databaseURL: 'https://portfolio-d2ea6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portfolio-d2ea6.firebasestorage.app',
    measurementId: 'G-ZSB9GD75QW',
  );
}
